/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "primary": "#7A0B2E",
        "primary-container": "#5C0822",
        "primary-fixed": "#FFD9E2",
        "primary-fixed-dim": "#FFB3C6",
        "on-primary": "#ffffff",
        "on-primary-container": "#FFD9E2",
        "on-primary-fixed": "#31000F",
        "on-primary-fixed-variant": "#610824",
        "secondary": "#5B6275",
        "secondary-container": "#E2E8F0",
        "secondary-fixed": "#E2E8F0",
        "secondary-fixed-dim": "#CBD5E1",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#475569",
        "on-secondary-fixed": "#0F172A",
        "on-secondary-fixed-variant": "#334155",
        "tertiary": "#7A0B2E",
        "tertiary-container": "#5C0822",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#FFD9E2",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "background": "#F8FAFC",
        "on-background": "#1E293B",
        "surface": "#FFFFFF",
        "surface-bright": "#F8FAFC",
        "surface-dim": "#E2E8F0",
        "surface-container": "#F1F5F9",
        "surface-container-low": "#F8FAFC",
        "surface-container-high": "#E2E8F0",
        "surface-container-highest": "#CBD5E1",
        "surface-container-lowest": "#FFFFFF",
        "surface-variant": "#F1F5F9",
        "on-surface": "#1E293B",
        "on-surface-variant": "#475569",
        "inverse-surface": "#0F172A",
        "inverse-on-surface": "#F8FAFC",
        "inverse-primary": "#FFB3C6",
        "outline": "#64748B",
        "outline-variant": "#E2E8F0",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "compact-padding": "8px",
        "comfortable-padding": "16px",
        "gutter": "16px",
        "container-margin": "24px",
        "section-gap": "32px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};